build:
  environment:
    selenium: true

  tests:
    before:
      - 'bin/console doctrine:database:create --if-not-exists'
      - 'bin/console server:start'
      - 'export SYMFONY_DEPRECATIONS_HELPER=weak'
