---
- hosts: production

  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes
      become: true

    - name: Install Aptitude
      apt:
        name: aptitude
        state: latest
      become: true

    - name: Upgrade existing packages
      apt:
        upgrade: safe
      become: true

    - name: Install the Git version control system
      apt:
        name: git
        state: latest
      become: true

    - name: Add PHP 7 personal package archive repository
      become: true
      apt_repository:
        repo: ppa:ondrej/php

    - name: Install PHP
      become: true
      apt:
        name: php7.1-cli
        state: latest
