---
- hosts: production

  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes
      become: true

    - name: Install Aptitude
      apt:
        name: aptitude
      become: true

    - name: Upgrade existing packages
      apt:
        upgrade: safe
      become: true

    - name: Install the Git version control system
      apt:
        name: git
      become: true
